-- agent: the assistant's memory and its job queue. Business data is NOT in here (see events.sql).
--
-- This is one of the project's TWO databases. On Supabase a project is a single Postgres database,
-- so the two are two schemas reached over two separate connections, each pinned to its own
-- search_path. Point AGENT_DB_URL and EVENTS_DB_URL at different projects and they become two
-- Postgres databases with no code change.

CREATE SCHEMA IF NOT EXISTS agent;
SET search_path TO agent;

CREATE TABLE IF NOT EXISTS thread (
    id          text PRIMARY KEY,
    student_id  text NOT NULL,
    created_at  timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS message (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    thread_id   text NOT NULL REFERENCES thread (id),
    seq         integer NOT NULL,
    role        text NOT NULL CHECK (role IN ('user', 'model')),
    text        text NOT NULL,
    created_at  timestamptz NOT NULL DEFAULT now(),
    UNIQUE (thread_id, seq)
);

-- A transcript you can edit is not a transcript. The database refuses, not the application.
-- Unqualified on purpose: search_path above decides which schema these land in, which is what
-- lets the demo and the tests run the same file into a schema of their own.
CREATE OR REPLACE FUNCTION message_append_only() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    RAISE EXCEPTION 'message is append-only: % rejected', TG_OP;
END;
$$;

DROP TRIGGER IF EXISTS message_no_change ON message;
CREATE TRIGGER message_no_change BEFORE UPDATE OR DELETE ON message
    FOR EACH ROW EXECUTE FUNCTION message_append_only();

CREATE TABLE IF NOT EXISTS run (
    id                text PRIMARY KEY,
    thread_id         text NOT NULL REFERENCES thread (id),
    status            text NOT NULL CHECK (status IN
                          ('queued', 'running', 'succeeded', 'failed', 'cancelled', 'dead')),
    model             text NOT NULL,
    tokens_in         integer NOT NULL DEFAULT 0,
    tokens_out        integer NOT NULL DEFAULT 0,
    attempts          integer NOT NULL DEFAULT 0,
    max_attempts      integer NOT NULL DEFAULT 3,
    available_at      double precision NOT NULL,   -- unix time; not claimable before this
    lease_owner       text,                        -- worker id holding the run
    lease_until       double precision,            -- unix time the lease expires
    cancel_requested  boolean NOT NULL DEFAULT false,
    error_code        text,
    created_at        timestamptz NOT NULL DEFAULT now(),
    started_at        timestamptz,
    finished_at       timestamptz
);

-- The claim query reads exactly this index: the queue stays fast when the run table does not.
CREATE INDEX IF NOT EXISTS run_claimable ON run (status, available_at, created_at);
CREATE INDEX IF NOT EXISTS run_leased ON run (status, lease_until);

CREATE TABLE IF NOT EXISTS run_step (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id      text NOT NULL REFERENCES run (id),
    seq         integer NOT NULL,
    kind        text NOT NULL CHECK (kind IN ('model', 'tool')),
    tokens_in   integer NOT NULL DEFAULT 0,
    tokens_out  integer NOT NULL DEFAULT 0,
    text        text,                              -- model steps: what the model said
    tool_calls  jsonb,                             -- model steps: [{"name", "args"}]
    created_at  timestamptz NOT NULL DEFAULT now(),
    UNIQUE (run_id, seq)
);

CREATE TABLE IF NOT EXISTS tool_call (
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_step_id      bigint NOT NULL UNIQUE REFERENCES run_step (id),
    tool_name        text NOT NULL,
    args             jsonb NOT NULL,
    result           jsonb NOT NULL,
    ok               boolean NOT NULL,
    latency_ms       integer NOT NULL,
    idempotency_key  text,
    created_at       timestamptz NOT NULL DEFAULT now()
);
