-- events: the campus events office's own data. The assistant's memory is in the agent schema.
--
-- The scarce thing is a seat. Two students asking for the last seat of the Robotics Bootcamp at the
-- same moment is the clash this project is built around: see event.seats_available, its CHECK, and
-- the version column that EventsDb.register uses for a compare-and-set.

CREATE SCHEMA IF NOT EXISTS events;
SET search_path TO events;

CREATE TABLE IF NOT EXISTS student (
    id                        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    roll_no                   text NOT NULL UNIQUE,
    name                      text NOT NULL,
    dept                      text NOT NULL,
    attendance_pct            integer NOT NULL CHECK (attendance_pct BETWEEN 0 AND 100),
    max_active_registrations  integer NOT NULL DEFAULT 2
);

CREATE TABLE IF NOT EXISTS event (
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title            text NOT NULL,
    category         text NOT NULL,
    venue            text NOT NULL,
    starts_at        timestamptz NOT NULL,
    seats_total      integer NOT NULL CHECK (seats_total >= 0),
    seats_available  integer NOT NULL CHECK (seats_available >= 0),
    version          integer NOT NULL DEFAULT 0,
    CHECK (seats_available <= seats_total)
);

-- Business rules live in data, not in a prompt. Change a row here and the assistant's answers
-- change on the next call, with no redeploy and no prompt edit.
CREATE TABLE IF NOT EXISTS policy (
    name   text PRIMARY KEY,
    value  integer NOT NULL
);

CREATE TABLE IF NOT EXISTS registration (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id  bigint NOT NULL REFERENCES student (id),
    event_id    bigint NOT NULL REFERENCES event (id),
    created_at  double precision NOT NULL,
    UNIQUE (student_id, event_id)          -- registering twice is one registration, not two
);

CREATE TABLE IF NOT EXISTS waitlist (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id  bigint NOT NULL REFERENCES student (id),
    event_id    bigint NOT NULL REFERENCES event (id),
    position    integer NOT NULL,
    created_at  double precision NOT NULL,
    UNIQUE (student_id, event_id),
    UNIQUE (event_id, position)            -- two students cannot hold the same place in the queue
);

CREATE TABLE IF NOT EXISTS notification (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    roll_no     text NOT NULL,
    message     text NOT NULL,
    dedupe_key  text NOT NULL UNIQUE,
    created_at  double precision NOT NULL
);

-- Keys live next to the side effects they guard, in the same database, so the effect and the
-- record that it happened commit or roll back together.
CREATE TABLE IF NOT EXISTS idempotency (
    key         text PRIMARY KEY,
    tool_name   text NOT NULL,
    result      jsonb NOT NULL,
    created_at  double precision NOT NULL
);
